#!/usr/bin/env bash

# Extracting fields using jq
name=$(jq -r '.name' data.json)
height=$(jq '.height' data.json)
weight=$(jq '.weight' data.json)
type=$(jq -r '.types[0].type.name' data.json)

# Converting  units using awk
formatted_height=$(echo "$height" | awk '{printf "%.1f", $1/10}')
formatted_weight=$(echo "$weight" | awk '{printf "%d", $1/10}')

# Capitalizing the  name and type using sed
name=$(echo "$name" | sed 's/.*/\u&/')
type=$(echo "$type" | sed 's/.*/\u&/')


echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
